# Generated by Django 5.2.17 on 2026-10-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccp_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("straight_through", "Straight-through"),
                    ("back_to_back", "Back-to-back"),
                    ("curves_digitizer", "Curves digitizer"),
                    ("curves_conversion", "Curves conversion"),
                    ("performance_evaluation", "Performance evaluation"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="casefile",
            name="kind",
            field=models.CharField(
                choices=[
                    ("curve_image", "Curve image"),
                    ("engauge_csv", "Engauge CSV"),
                    ("plant_data", "Plant data"),
                    ("curve_pdf", "Curve PDF"),
                ],
                max_length=20,
            ),
        ),
    ]
