# Impeller { #ccp.Impeller }

```python
Impeller(points)
```

An impeller with a performance map.

Impeller instance is initialized with the list of points.
The created instance will hold the dimensional points used in instantiation.
Curves will be generated from points close in similarity.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                  | Default    |
|--------|--------|------------------------------|------------|
| points | list   | List with ccp.Point objects. | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name     | Type         | Description   |
|----------|--------------|---------------|
| impeller | ccp.Impeller |               |

## Methods

| Name | Description |
| --- | --- |
| [convert_from](#ccp.Impeller.convert_from) | Convert performance map from an impeller. |
| [curve](#ccp.Impeller.curve) | Calculate specific point in the performance map. |
| [export_to_excel](#ccp.Impeller.export_to_excel) | Export curves to excel file. |
| [load](#ccp.Impeller.load) | Load impeller from toml file. |
| [load_from_dict](#ccp.Impeller.load_from_dict) | Create points from dict object. |
| [load_from_dict_isis](#ccp.Impeller.load_from_dict_isis) | Create points from dict object available in the ISIS platform. |
| [load_from_engauge_csv](#ccp.Impeller.load_from_engauge_csv) | Convert points from csv generated by engauge to csv with 6 points at same flow for use on hysys. |
| [point](#ccp.Impeller.point) | Calculate specific point in the performance map. |
| [save](#ccp.Impeller.save) | Save impeller to a toml file. |
| [save_hysys_csv](#ccp.Impeller.save_hysys_csv) | Save curve to a csv with hysys format. |
| [save_isis_txt](#ccp.Impeller.save_isis_txt) | Save curves to a csv with isis format. |

### convert_from { #ccp.Impeller.convert_from }

```python
Impeller.convert_from(original_impeller, suc=None, find='speed', speed=None)
```

Convert performance map from an impeller.

#### Parameters {.doc-section .doc-section-parameters}

| Name              | Type                        | Description                                                                                                                                                                                                             | Default    |
|-------------------|-----------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| original_impeller | (ccp.Impeller, list)        | The original impeller. A list of impeller can also be passed. In this case the curves will be converted based on the impeller with the closest suction speed of sound to the new suction condition.                     | _required_ |
| suc               | ccp.State                   | The new suction condition to which we want to convert to.                                                                                                                                                               | `None`     |
| find              | str                         | The method in which the curves will be converted. For now only 'speed' is implemented, which means that, based on volume ratio, we calculate new values of speed for each curve and the respective discharge condition. | `'speed'`  |
| speed             | (float, pint.Quantity, str) | Desired speed. If find="speed", this can be None or 'same' to keep the same speed values available in the original_impeller.                                                                                            | `None`     |

#### Returns {.doc-section .doc-section-returns}

| Name               | Type         | Description                                                                             |
|--------------------|--------------|-----------------------------------------------------------------------------------------|
| converted_impeller | ccp.Impeller | The new impeller with the converted performance map for the required suction condition. |

### curve { #ccp.Impeller.curve }

```python
Impeller.curve(speed=None)
```

Calculate specific point in the performance map.

Given a speed this method will calculate a curve in the
impeller map according to these arguments.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                   | Description    | Default   |
|--------|------------------------|----------------|-----------|
| speed  | (pint.Quantity, float) | Speed (rad/s). | `None`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description                   |
|--------|-----------|-------------------------------|
| curve  | ccp.Curve | Point in the performance map. |

### export_to_excel { #ccp.Impeller.export_to_excel }

```python
Impeller.export_to_excel(path_name=None)
```

Export curves to excel file.

### load { #ccp.Impeller.load }

```python
Impeller.load(file)
```

Load impeller from toml file.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                | Description                          | Default    |
|--------|---------------------|--------------------------------------|------------|
| file   | str or pathlib.Path | Filename to which the data is saved. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name     | Type         | Description      |
|----------|--------------|------------------|
| impeller | ccp.Impeller | Impeller object. |

### load_from_dict { #ccp.Impeller.load_from_dict }

```python
Impeller.load_from_dict(
    suc,
    head_curves=None,
    eff_curves=None,
    power_curves=None,
    power_shaft_curves=None,
    pressure_ratio_curves=None,
    disch_T_curves=None,
    b=Q_(0.005, 'm'),
    D=Q_(0.5, 'm'),
    number_of_points=10,
    flow_units='m**3/s',
    flow_units_head=None,
    flow_units_eff=None,
    flow_units_power=None,
    flow_units_power_shaft=None,
    flow_units_pressure_ratio=None,
    flow_units_disch_T=None,
    head_units='J/kg',
    eff_units='dimensionless',
    pressure_ratio_units='dimensionless',
    disch_T_units='degK',
    power_units='W',
    power_shaft_units='W',
    power_losses_units='W',
    speed_units='RPM',
)
```

Create points from dict object.

In this case the dict is in the following format:

curve = {
    '10000': {
        'x1': [list with flow values],
        'x2': [list with head or eff values]
        'x3': power losses value},
    ...}
Where 10000 is the speed for that curve.

suc : ccp.State
    Suction state.
head_curves : dict
    Dict with head/flow values.
eff_curves : dict
    Dict with eff/flow values.
power_curves : dict
    Dict with power/flow values.
b : float, pint.Quantity
    Impeller width at the outer blade diameter (m).
D : float, pint.Quantity
    Impeller outer diameter (m).
number_of_points : int
    Number of points that will be interpolated.
flow_units : str
    Flow units used in the dict.
flow_units_head: str
    Flow units used in the dict for head curves.
    Only needed when flow units for head curve differs from other curves.
flow_units_eff: str
    Flow units used  in the dict for efficiency curves.
    Only needed when flow units for efficiency curve differs from other curves.
flow_units_power: str
    Flow units used  in the dict for power curves.
    Only needed when flow units for power curve differs from other curves.
flow_units_power_shaft: str
    Flow units used in the dict for shaft power curves.
    Only needed when flow units for power curve differs from other curves.
flow_units_pressure_ratio: str
    Flow units used  in the dict for pressure ratio curves.
    Only needed when flow units for efficiency curve differs from other curves.
flow_units_disch_T: str
    Flow units used  in the dict for discharge Temperature curves.
    Only needed when flow units for efficiency curve differs from other curves.
head_units : str
    Head units used in the dict.
    If the curve head units are in meter you can use: head_units="m*g0".
eff_units : str
    Dimensionless.
power_units : str
    Power units used in the dict.
power_shaft_units : str
    Shaft power units used in the dict.
power_losses_units : str
    Mechanical power losses units used in the dict.
pressure_ratio_units : str
    Pressure ratio units used in the dict.
disch_T_units : str
    Discharge temperature units used in the dict.
speed_units : str
    Speed units used in the dict.

### load_from_dict_isis { #ccp.Impeller.load_from_dict_isis }

```python
Impeller.load_from_dict_isis(
    suc,
    head_curves,
    eff_curves,
    b=Q_(0.005, 'm'),
    D=Q_(0.5, 'm'),
    number_of_points=10,
    flow_units='m**3/s',
    head_units='J/kg',
    speed_units='RPM',
)
```

Create points from dict object available in the ISIS platform.

The dict is in the following format:
   head_curves_dict = [
{
    "z": 11373,
    "points": [
        {"x": 94529, "y": 148.586},
        {"x": 98641, "y": 148.211},
        {"x": 101554, "y": 147.837},
    ...]
...,
},
]

Where z is the speed and each point is described as a dict with x and y
pair where x is the flow and y is the head or eff.

suc : ccp.State
    Suction state.
head_curve : dict
    Dict with head/flow values.
eff_curve : dict
    Dict with head/flow values.
b : float, pint.Quantity
    Impeller width at the outer blade diameter (m).
D : float, pint.Quantity
    Impeller outer diameter (m).
number_of_points : int
    Number of points that will be interpolated.
flow_units : str
    Flow units used in the dict.
head_units : str
    Head units used in the dict.
    If the curve head units are in meter you can use: head_units="m*g0".
speed_units : str
    Speed units used in the dict.

#### Examples {.doc-section .doc-section-examples}

```python
>>> import ccp
>>> composition_fd = dict(
...    n2=0.4,
...    co2=0.22,
...    methane=92.11,
...    ethane=4.94,
...    propane=1.71,
...    ibutane=0.24,
...    butane=0.3,
...    ipentane=0.04,
...    pentane=0.03,
...    hexane=0.01,
... )
>>> suc_fd = State(p=Q_(3876, "kPa"), T=Q_(11, "degC"), fluid=composition_fd)
>>> imp = ccp.Impeller.load_from_dict_isis(
...    suc=suc_fd,
...    head_curves=head_curves_dict,
...    eff_curves=eff_curves_dict,
...    b=Q_(10.6, "mm"),
...    D=Q_(390, "mm"),
...    number_of_points=6,
...    flow_units="kg/h",
...    head_units="kJ/kg",
... )
```

### load_from_engauge_csv { #ccp.Impeller.load_from_engauge_csv }

```python
Impeller.load_from_engauge_csv(
    suc,
    curve_name,
    curve_path,
    b=Q_(0.005, 'm'),
    D=Q_(0.5, 'm'),
    number_of_points=10,
    flow_units='m**3/s',
    flow_units_head=None,
    flow_units_eff=None,
    flow_units_power=None,
    flow_units_power_shaft=None,
    flow_units_pressure_ratio=None,
    flow_units_disch_T=None,
    head_units='J/kg',
    eff_units='dimensionless',
    power_units='W',
    power_shaft_units='W',
    power_losses_units='W',
    pressure_ratio_units='dimensionless',
    disch_T_units='degK',
    speed_units='RPM',
    **kwargs,
)
```

Convert points from csv generated by engauge to csv with 6 points at same flow for use on hysys.

The csv files should be generated with engauge with the following procedure:
First, copy the image of the curve to your clipboard, then inside engauge digitizer:
    - Edit -> Paste as new
    - Name each curve with their respective speed value (e.g. 10322);
    - If the curve is for shaft power, you can add the power loss next to the speed value (e.g. 10322, 82);
    - On Axis Point -> add 3 reference points
    - Select the curve (e.g. 10322 would be the curve for 10322 RPM)
    - Select the points using the segment fill tool;
    - Select the next curve and points...
    - Settings -> Export Setup -> Select:
    - Raws X's and Y's ; One curve on each line
Files should be saved with the following convention:
    - <curve-name>-head.csv
    - <curve-name>-eff.csv

suc : ccp.State
    Suction state.
curve_path : pathlib.Path
    Path to the curves.
curve_name : str
    Name for head and efficiency curve.
    Curves should have names <curve_name>-head.csv and <curve-name>-eff.csv.
b : float, pint.Quantity
    Impeller width at the outer blade diameter (m).
D : float, pint.Quantity
    Impeller outer diameter (m).
number_of_points : int
    Number of points that will be interpolated.
flow_units : str
    Flow units used when extracting data with engauge.
flow_units_head: str
    Flow units used when extracting data with engauge for head curves.
    Only needed when flow units for head curve differs from other curves.
flow_units_eff: str
    Flow units used when extracting data with engauge for efficiency curves.
    Only needed when flow units for efficiency curve differs from other curves.
flow_units_power: str
    Flow units used when extracting data with engauge for power curves.
    Only needed when flow units for power curve differs from other curves.
flow_units_power_shaft: str
    Flow units used when extracting data with engauge for shaft power curves.
    Only needed when flow units for power curve differs from other curves.
flow_units_pressure_ratio: str
    Flow units used when extracting data with engauge for pressure ratio curves.
    Only needed when flow units for power curve differs from other curves.
flow_units_disch_T: str
    Flow units used when extracting data with engauge for discharge temperature curves.
    Only needed when flow units for efficiency curve differs from other curves.
head_units : str
    Head units used when extracting data with engauge.
    If the curve head units are in meter you can use: head_units="m*g0".
eff_units : str
    Dimensionless.
power_units : str
    Power units used when extracting data with engauge.
power_shaft_units : str
    Shaft power units used when extracting data with engauge.
power_losses_units : str
    Power losses units used when extracting data with engauge.
pressure_ratio_units : str
    Pressure ratio units used when extracting data with engauge.
disch_T_units : str
    Discharge temperature units used when extracting data with engauge.
speed_units : str
    Speed units used when extracting data with engauge.

### point { #ccp.Impeller.point }

```python
Impeller.point(flow_v=None, flow_m=None, speed=None)
```

Calculate specific point in the performance map.

Given a volumetric flow and a speed this method will calculate a point in the
impeller map according to these arguments.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                   | Description             | Default   |
|--------|------------------------|-------------------------|-----------|
| flow_v | (pint.Quantity, float) | Volumetric flow (m³/s). | `None`    |
| flow_m | (pint.Quantity, float) | Mass flow (kg/s).       | `None`    |
| speed  | (pint.Quantity, float) | Speed (rad/s).          | `None`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description                   |
|--------|-----------|-------------------------------|
| point  | ccp.Point | Point in the performance map. |

### save { #ccp.Impeller.save }

```python
Impeller.save(file)
```

Save impeller to a toml file.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                | Description                          | Default    |
|--------|---------------------|--------------------------------------|------------|
| file   | str or pathlib.Path | Filename to which the data is saved. | _required_ |

### save_hysys_csv { #ccp.Impeller.save_hysys_csv }

```python
Impeller.save_hysys_csv(curve_dir)
```

Save curve to a csv with hysys format.

curve_path: pathlib.Path
    Path for directory where the files will be saved.

### save_isis_txt { #ccp.Impeller.save_isis_txt }

```python
Impeller.save_isis_txt(file, parameter)
```

Save curves to a csv with isis format.

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type                | Description                                                                   | Default    |
|-----------|---------------------|-------------------------------------------------------------------------------|------------|
| file      | str or pathlib.Path | Filename to which the data is saved.                                          | _required_ |
| parameter | str                 | Parameter name. Can be "head", "eff", "power", "pressure_ratio" or "disch_T". | _required_ |

#### Examples {.doc-section .doc-section-examples}

```python
>>> impeller.save_isis_txt("head.txt", parameter="head")
```