name: Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up REFPROP
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git clone https://github.com/raphaeltimbo/REFPROP.git

    # Installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      # Running pytest
      - name: Test with pytest
        run: |
          export RPPREFIX="$(echo ${HOME}/REFPROP/build")
          ls REFPROP/build
          pip install pytest
          pytest ccp
      - name: Code Lint
        run: |
          black --check ccp
        if: success()
